- name: Instalando Metrics Kubernetes.
  shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml
  register: weavenet_result
  when: INSTALL_METRICS|bool

#https://medium.com/@cagri.ersen/kubernetes-metrics-server-installation-d93380de008  

#command:
#  - /metrics-server
#  - --metric-resolution=5s
#  - --kubelet-preferred-address-types=InternalIP
#  - --kubelet-insecure-tls
