#- name: Instalando Ingress NGINX Kubernetes.
#  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/deploy.yaml
#  register: weavenet_result
#  when: INSTALL_INGRESS|bool


- name: Criando namespace ingress-nginx NGINX Kubernetes.
  shell: kubectl create namespace ingress-nginx
  when: INSTALL_INGRESS|bool

- name: Habilitando repo HELM Ingress NGINX Kubernetes.
  shell: helm repo add nginx-stable https://helm.nginx.com/stable
  when: INSTALL_INGRESS|bool

- name: Atualizando repo HELM Ingress NGINX Kubernetes.
  shell: helm repo update
  when: INSTALL_INGRESS|bool

- name: Instalando repo HELM Ingress NGINX Kubernetes.
  shell: helm install my-ingress nginx-stable/nginx-ingress --namespace=ingress-nginx --set rbac.create=true
  when: INSTALL_INGRESS|bool

- name: Instalando CertManager NGINX Kubernetes.
  shell: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
  when: INSTALL_INGRESS|bool


